### ISSUE TITLE
CXX flags

### ISSUE THREAD

**Issue by richard91089** [aantropov/sailor#2]
i get a problem with the cxx flags when i try building your project in VS 2022. My operating system is x64 and not x32, so should i change the flag from /DWIN32 to /DWIN64? the errors also include not finding CMakeLists.txt in some of your other folders.

**Comment by aantropov** [comment]
@richard91089, Actually, the project is targeted to x64 platform, but still has deps on the third parties (you can find all the submodules under 'External' folder). 

'the errors also include not finding CMakeLists.txt in some of your other folders.' 
Have you updated all the git submodules?

'yaml-cpp', 'assimp', 'spirv_reflect' and '_nlohmann_json_' passes /DWIN32 as a cxx flag, if I'm not mistaken.
